---
title: "Test Shiny"
author: "MECI"
date: "18/02/2021"
output: html_document
runtime: shiny
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, eval=T)

# packages utiles
library(knitr)
library(tidyverse)
library(ggplot2)
library(sf)
library(cartography)
library(shiny)

# fonctions utiles
source("fonctions/mes_fonctions_V2.R")

# on charge les fichers de données
indiv <- readRDS("data/indiv2017.Rdata")
meta <- readRDS("data/indiv2017_meta.Rdata")
map_iris <-readRDS("data/map_iris.Rdata")

# On crée un tableau d'exemple 
tab<-indiv %>% select(IRIS,VOIT,LPRM, IPONDI) %>% 
            mutate(LPRM_1 = case_when(LPRM == "1" ~ "1", TRUE ~ "0"),
                   COM = substr(IRIS,1,5))
# On sélectionne les communes ayant au moins 10 iris
listcom <- names(table(tab$COM))[table(tab$COM)>10]
listcom <-listcom[listcom !="ZZZZZ"]


```



## Inputs et Outputs


```{r eruptions, echo=FALSE}
inputPanel(
  selectInput(inputId = "com",
              label = "Choix de la commune",
              choices = listcom,
              selected = "94370")
)



renderPlot({map_count_iris(data = tab,
                           map = map_iris,
                           codecom = input$com,
                           var = VOIT,
                           list_mod = "0",
                           mod = 0,
                           titre = "XXX"
                           )
    
   })

```
